### ISSUE TITLE
java.lang.UnsatisfiedLinkError. org.robovm:robopods-google-mobile-ads-ios:1.14.0

### ISSUE THREAD

**Issue by ldthai** [robovm/robovm-robopods#105]
Hello
I got error with org.robovm:robopods-google-mobile-ads-ios:1.14.0
`java.lang.UnsatisfiedLinkError: Optional @GlobalValue method org/robovm/pods/google/mobileads/GADAdSize.SmartBannerPortrait()Lorg/robovm/pods/google/mobileads/GADAdSize; not bound
	at org.robovm.pods.google.mobileads.GADAdSize.SmartBannerPortrait(GADAdSize.java)
	at com.huesoft.rongvang.IOSADSManager.initADSBanner(IOSADSManager.java:65)
	at com.huesoft.rongvang.IOSLauncher.didFinishLaunching(IOSLauncher.java:181)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.$cb$application$didFinishLaunchingWithOptions$(IOSApplication.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:413)
	at com.huesoft.rongvang.IOSLauncher.main(IOSLauncher.java:169)`

org.robovm:robopods-google-mobile-ads-ios:1.12.0 fine

**Comment by BlueRiverInteractive** [comment]
With 1.14.0 you will have to manually add the binaries to you project. Please see the readme of the robopod: 
https://github.com/robovm/robovm-robopods/tree/master/google-mobile-ads/ios#3rd-party-native-framework

**Comment by ldthai** [comment]
worked! thank you!
