### ISSUE TITLE
Google Analytics robopods 1.14 broken when using GGLContext

### ISSUE THREAD

**Issue by keesvandieren** [robovm/robovm-robopods#107]
Hi,

We try to upgrade our existing app (working fine in 1.13) to 1.14.

It fails with the following exception:

Execute: GGLContext.getSharedInstance().configure()
java.lang.ExceptionInInitializerError
    at org.robovm.samples.robopods.google.analytics.ios.GoogleAnalyticsApp.didFinishLaunching(GoogleAnalyticsApp.java:40)
    at org.robovm.samples.robopods.google.analytics.ios.GoogleAnalyticsApp.$cb$application$didFinishLaunchingWithOptions$(GoogleAnalyticsApp.java)
    at org.robovm.apple.uikit.UIApplication.main(Native Method)
    at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:413)
    at org.robovm.samples.robopods.google.analytics.ios.GoogleAnalyticsApp.main(GoogleAnalyticsApp.java:59)
Caused by: org.robovm.objc.ObjCClassNotFoundException: GGLContext
    at org.robovm.objc.ObjCClass.getByType(ObjCClass.java:251)
    at org.robovm.pods.google.GGLContext.<clinit>(GGLContext.java:43)

The installation guide (here: https://github.com/robovm/robovm-robopods/tree/master/google-analytics/ios )  mentions this code block:

```
try {
    GGLContext.getSharedInstance().configure();
} catch (NSErrorException e) {
    System.err.println("Error configuring the Google context: " + e.getError());
}
```

Adding that block, crashes the robovm sample for Google Analytics.

It is demonstrated in this commit:

https://github.com/squins/robovm-samples/commit/045953d523c9f5c78beafc82dfd0dd29460fde45

Maybe native classes for https://github.com/robovm/robovm-robopods/tree/master/google-apis are missing?

**Comment by kizinfo** [comment]
certainly seems like something is missing. can still use GA without the configuration file 
GAI.getSharedInstance().getTracker("UA-XXXXXXX-X");
after first time it sticks as the default tracker.

**Comment by krasanen** [comment]
Facing the same issue, cannot get google-mobile-adds-ios to work anymore. It fails at run time to "org.robovm.objc.ObjCClassNotFoundException: GGLContext" when "GGLContextMobileAds.getSharedInstance().configure();" is called. Also fails to missing classes when trying to configure adds with separate add instances instead of "GoogleService-Info.plist" configuration file. It seems that natives are missing for some reason? Is there a way to use them without GGLContext until this is solved?

**Comment by julienvillegas** [comment]
I have the same issue (with version 1.14)

```
java.lang.ExceptionInInitializerError
    at org.robovm.pods.google.GGLContextMobileAds.getSharedInstance(GGLContextMobileAds.java:33)
Caused by: org.robovm.objc.ObjCClassNotFoundException: GGLContext
    at org.robovm.objc.ObjCClass.getByType(ObjCClass.java:251)
    at org.robovm.pods.google.GGLContext.<clinit>(GGLContext.java:43)
    ... 7 more
```

Apparently this is also raised on RoboVM group since March 3rd : https://groups.google.com/forum/#!topic/robovm/V_ity6VXJIo

**Comment by krasanen** [comment]
Found a workaround to get classes found. Added libAdIdAccess.a, libGGLCore.a and libGoogleAnalyticsServices.a to ios/libs.

**Comment by julienvillegas** [comment]
Sounds good. I cannot find those files. Where can I find them?

**Comment by keesvandieren** [comment]
This gives a hint: http://stackoverflow.com/questions/31165164/libadidaccess-a-location

**Comment by julienvillegas** [comment]
Ok,
I god rid of the issue, was using GGLContext.getSharedInstance().configure(); to adMobs, but instead of of loading the add ID from the google configuration file through:

```
GGLContext.getSharedInstance().configure();
interstitial = new GADInterstitial(GGLContextMobileAds.getSharedInstance().getAdUnitIDForInterstitialTest());
```

I simply passed the adMob ID manually as such:

`interstitial = new GADInterstitial("ca-app-pub-xxxx/xxxx");`
