### ISSUE TITLE
Can't create IPA, gpg 1.14.0, GoogleSignIn 1.14.0, Libgdx 1.9.2, Robovm 1.12.0

### ISSUE THREAD

**Issue by ldthai** [robovm/robovm-robopods#111]
Hello All
I have setup Google Play Services and Google SignIn.
I got error:
`[ERROR] Undefined symbols for architecture armv7:
[ERROR]   "_OBJC_IVAR_$_GTLObject.surrogates_", referenced from:
[ERROR]       -[GTLObject(GPGAdditions) encodeWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]       -[GTLObject(GPGAdditions) initWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]   "_OBJC_IVAR_$_GTLObject.userProperties_", referenced from:
[ERROR]       -[GTLObject(GPGAdditions) encodeWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]       -[GTLObject(GPGAdditions) initWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]   "_OBJC_CLASS_$_GTLPlusPerson", referenced from:
[ERROR]       objc-class-ref in gpg(GPGPlayerServiceMock.o)
[ERROR]   "_OBJC_METACLASS_$_GTLCollectionObject", referenced from:
[ERROR]       _OBJC_METACLASS_$_GTLGamesEventDefinitionListResponse in gpg(GTLGamesEventDefinitionListResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesLeaderboardListResponse in gpg(GTLGamesLeaderboardListResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesPlayerAchievementListResponse in gpg(GTLGamesPlayerAchievementListResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesPlayerEventListResponse in gpg(GTLGamesPlayerEventListResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesPlayerLeaderboardScoreListResponse in gpg(GTLGamesPlayerLeaderboardScoreListResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesRoomList in gpg(GTLGamesRoomList.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesTurnBasedMatchList in gpg(GTLGamesTurnBasedMatchList.o)
[ERROR]       ...
[ERROR]   "_OBJC_CLASS_$_GTLServicePlus", referenced from:
[ERROR]       objc-class-ref in gpg(GPGPlayerServiceMock.o)
[ERROR]       objc-class-ref in gpg(GPGPlayerPickerViewControllerDelegateMock.o)
[ERROR]       objc-class-ref in gpg(libgpg.a-armv7-master.o)
[ERROR]   "_OBJC_METACLASS_$_GTLServiceTicket", referenced from:
[ERROR]       _OBJC_METACLASS_$_GPGServiceTicket in gpg(GPGService.o)
[ERROR]   "_OBJC_CLASS_$_GTLQueryPlus", referenced from:
[ERROR]       objc-class-ref in gpg(GPGPlayerServiceMock.o)
[ERROR]       objc-class-ref in gpg(GPGPlayerPickerViewControllerDelegateMock.o)
[ERROR]       objc-class-ref in gpg(libgpg.a-armv7-master.o)
[ERROR]   "_OBJC_CLASS_$_GTLServiceTicket", referenced from:
[ERROR]       _OBJC_CLASS_$_GPGServiceTicket in gpg(GPGService.o)
[ERROR]   "_OBJC_IVAR_$_GTLObject.json_", referenced from:
[ERROR]       -[GTLObject(GPGAdditions) encodeWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]       -[GTLObject(GPGAdditions) initWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]   "_OBJC_METACLASS_$_GTLQuery", referenced from:
[ERROR]       _OBJC_METACLASS_$_GTLQueryGamesManagement in gpg(GTLQueryGamesManagement.o)
[ERROR]       _OBJC_METACLASS_$_GTLQueryGames in gpg(GTLQueryGames.o)
[ERROR]      (maybe you meant: _OBJC_METACLASS_$_GTLQueryGamesManagement, _OBJC_METACLASS_$_GTLQueryGames )
[ERROR]   "_OBJC_CLASS_$_OpenInChromeController", referenced from:
[ERROR]       objc-class-ref in gpg(GPGSettingsViewController.o)
[ERROR]   "_OBJC_METACLASS_$_GTLService", referenced from:
[ERROR]       _OBJC_METACLASS_$_GTLServiceGames in gpg(GTLServiceGames.o)
[ERROR]      (maybe you meant: _OBJC_METACLASS_$_GTLServiceGames)
[ERROR]   "_kGTMOAuth2ErrorUnsupportedGrantType", referenced from:
[ERROR]       ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
[ERROR]      (maybe you meant: _GSDK_kGTMOAuth2ErrorUnsupportedGrantType)
[ERROR]   "_OBJC_CLASS_$_GTMLogger", referenced from:
[ERROR]       objc-class-ref in gpg(GPGAchievementToastView.o)
[ERROR]       objc-class-ref in gpg(GPGLeaderboardScoresViewController.o)
[ERROR]       objc-class-ref in gpg(GPGLocalization.o)
[ERROR]       objc-class-ref in gpg(GPGLogger.o)
[ERROR]       objc-class-ref in gpg(GPGManager.o)
[ERROR]       objc-class-ref in gpg(GPGProfileViewController.o)
[ERROR]       objc-class-ref in gpg(GPGPushToken.o)
[ERROR]       ...
[ERROR]   "_kGTMOAuth2ErrorInvalidScope", referenced from:
[ERROR]       ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
[ERROR]      (maybe you meant: _GSDK_kGTMOAuth2ErrorInvalidScope)
[ERROR]   "_kGTMOAuth2ErrorInvalidRequest", referenced from:
[ERROR]       ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
[ERROR]      (maybe you meant: _GSDK_kGTMOAuth2ErrorInvalidRequest)
[ERROR]   "_OBJC_IVAR_$_GTLObject.childCache_", referenced from:
[ERROR]       -[GTLObject(GPGAdditions) encodeWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]       -[GTLObject(GPGAdditions) initWithCoder:] in gpg(GTLObject+GPGAdditions.o)
[ERROR]   "_kGTMOAuth2ErrorInvalidGrant", referenced from:
[ERROR]       ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
[ERROR]      (maybe you meant: _GSDK_kGTMOAuth2ErrorInvalidGrant)
[ERROR]   "_OBJC_METACLASS_$_GTLObject", referenced from:
[ERROR]       _OBJC_METACLASS_$_GTLGamesManagementHiddenPlayer in gpg(GTLGamesManagementHiddenPlayer.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesManagementPlayer in gpg(GTLGamesManagementPlayer.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesAchievementDefinition in gpg(GTLGamesAchievementDefinition.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesAchievementIncrementResponse in gpg(GTLGamesAchievementIncrementResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesAchievementSetStepsAtLeastResponse in gpg(GTLGamesAchievementSetStepsAtLeastResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesAchievementUpdateResponse in gpg(GTLGamesAchievementUpdateResponse.o)
[ERROR]       _OBJC_METACLASS_$_GTLGamesCategory in gpg(GTLGamesCategory.o)
[ERROR]       ...
[ERROR]   "_OBJC_CLASS_$_GTMOAuth2Authentication", referenced from:
[ERROR]       objc-class-ref in gpg(GPGManager.o)
[ERROR]       objc-class-ref in gpg(libgpg.a-armv7-master.o)
[ERROR]   "_OBJC_CLASS_$_GTLQuery", referenced from:
[ERROR]       _OBJC_CLASS_$_GTLQueryGamesManagement in gpg(GTLQueryGamesManagement.o)
[ERROR]       _OBJC_CLASS_$_GTLQueryGames in gpg(GTLQueryGames.o)
[ERROR]      (maybe you meant: _OBJC_CLASS_$_GTLQueryGames, _OBJC_CLASS_$_GTLQueryGamesManagement )
[ERROR]   "_OBJC_CLASS_$_GTLObject", referenced from:
[ERROR]       _OBJC_CLASS_$_GTLGamesManagementHiddenPlayer in gpg(GTLGamesManagementHiddenPlayer.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesManagementPlayer in gpg(GTLGamesManagementPlayer.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesAchievementDefinition in gpg(GTLGamesAchievementDefinition.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesAchievementIncrementResponse in gpg(GTLGamesAchievementIncrementResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesAchievementSetStepsAtLeastResponse in gpg(GTLGamesAchievementSetStepsAtLeastResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesAchievementUpdateResponse in gpg(GTLGamesAchievementUpdateResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesCategory in gpg(GTLGamesCategory.o)
[ERROR]       ...
[ERROR]   "_OBJC_CLASS_$_GTLService", referenced from:
[ERROR]       _OBJC_CLASS_$_GTLServiceGames in gpg(GTLServiceGames.o)
[ERROR]      (maybe you meant: _OBJC_CLASS_$_GTLServiceGames)
[ERROR]   "_OBJC_CLASS_$_GTMOAuth2SignIn", referenced from:
[ERROR]       objc-class-ref in gpg(GPGManager.o)
[ERROR]       objc-class-ref in gpg(libgpg.a-armv7-master.o)
[ERROR]   "_OBJC_CLASS_$_GTLCollectionObject", referenced from:
[ERROR]       _OBJC_CLASS_$_GTLGamesEventDefinitionListResponse in gpg(GTLGamesEventDefinitionListResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesLeaderboardListResponse in gpg(GTLGamesLeaderboardListResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesPlayerAchievementListResponse in gpg(GTLGamesPlayerAchievementListResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesPlayerEventListResponse in gpg(GTLGamesPlayerEventListResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesPlayerLeaderboardScoreListResponse in gpg(GTLGamesPlayerLeaderboardScoreListResponse.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesRoomList in gpg(GTLGamesRoomList.o)
[ERROR]       _OBJC_CLASS_$_GTLGamesTurnBasedMatchList in gpg(GTLGamesTurnBasedMatchList.o)
[ERROR]       ...
[ERROR]   "_kGTMOAuth2ErrorInvalidClient", referenced from:
[ERROR]       ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
[ERROR]      (maybe you meant: _GSDK_kGTMOAuth2ErrorInvalidClient)
[ERROR]   "_kGTMOAuth2ErrorUnauthorizedClient", referenced from:
[ERROR]       ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
[ERROR]      (maybe you meant: _GSDK_kGTMOAuth2ErrorUnauthorizedClient)
[ERROR] ld: symbol(s) not found for architecture armv7
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't create IPA
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm6273734048014657040.tmp/thumbv7/IOSLauncher -arch armv7 -Wl,-filelist,/Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm6273734048014657040.tmp/thumbv7/objects0 -L /Users/ldthai/.robovm-sdks/robovm-1.14.0/lib/vm/ios/thumbv7 -ObjC -Xlinker -alias_list -Xlinker /Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm6273734048014657040.tmp/thumbv7/aliased_symbols -exported_symbols_list /Users/ldthai/Library/Caches/AndroidStudio1.5/tmp/robovm6273734048014657040.tmp/thumbv7/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Volumes/DATA/AM/FruitBubbleShoot/Development/FruitBubbleShoot_GDX192/ios/libs -fPIC -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -lrobovm-bc -lrobovm-core -lgc -lpthread -ldl -lm -lz -framework Foundation -framework AdSupport -framework AudioToolbox -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreTelephony -framework EventKit -framework EventKitUI -framework MediaPlayer -framework MessageUI -framework QuartzCore -framework StoreKit -framework SystemConfiguration -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreLocation -framework CoreMotion -framework CoreText -framework Security -framework UIKit -framework OpenGLES -framework OpenAL -framework GoogleSignIn -framework gpg -framework GoogleMobileAds -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/dcb4bf31791a84f9cfb5a8098ab1eaf7.extracted/META-INF/robovm/ios/thumbv7/librobovm-rt-android.a -liconv -lsqlite3 -lz -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/3aba2d18b9add9eaca2972f68a4520fc.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/ldthai/.robovm/cache/ios/thumbv7/release/cp/3aba2d18b9add9eaca2972f68a4520fc.extracted/META-INF/robovm/ios/libs/libObjectAL.a -lc++ -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:348)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:398)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:282)
    at org.robovm.compiler.target.ios.AppleDeviceTarget.doBuild(AppleDeviceTarget.java:528)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:276)
    at org.robovm.compiler.Linker.link(Linker.java:439)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:411)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:741)
    at org.robovm.idea.compilation.RoboVmCompileTask$1.doCompile(RoboVmCompileTask.java:109)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:59)`

thanks!

**Comment by ldthai** [comment]
i found slution : https://groups.google.com/forum/#!topic/robovm/ZRgcZwxetMo
thanks
