### ISSUE TITLE
On adding third party sdk as described in document of Google Mobile Ads, here is error in libgdx

### ISSUE THREAD

**Issue by prakharprakhar89** [robovm/robovm-robopods#118]
[INFO] Building ios binary /Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/IOSLauncher
[INFO] "/Applications/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -o "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/IOSLauncher" -arch armv7 "-Wl,-filelist,/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/objects0" -L /Users/ibcmobile/.robovm-sdks/robovm-2.1.0/lib/vm/ios/thumbv7 -ObjC -Xlinker -alias_list -Xlinker "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/aliased_symbols" -exported_symbols_list "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/exported_symbols" -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-login/1.14.0/1a3cc419790b1abd94c4434cae633fd4e0082322/robopods-facebook-ios-login-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-share/1.14.0/3ebade83088ee749b6d74917b8b24a0b981b3cd4/robopods-facebook-ios-share-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-core/1.14.0/39470ef9e2ca5bc3c712c4d7818e56a6660cf01d/robopods-facebook-ios-core-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-messenger/1.14.0/7d9728a9f8fdf6f3a360aff264b6c6b1bcf7c05e/robopods-facebook-ios-messenger-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-bolts-ios/1.14.0/9af31651b319253310c5d34d265bb92de70ddfe7/robopods-bolts-ios-1.14.0.jar.extracted/META-INF/robovm/ios/libs "-F/Users/ibcmobile/Desktop/Platform Dash/ios/libs" -fPIC -miphoneos-version-min=7.0 
[INFO]     -isysroot "/Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk" -lrobovm-bc -force_load /Users/ibcmobile/.robovm-sdks/robovm-2.1.0/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework FBSDKLoginKit -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreMotion -framework StoreKit -framework FBSDKShareKit -framework FBSDKCoreKit -framework Bolts -framework AdSupport -framework AudioToolbox -framework CoreTelephony -framework EventKit -framework EventKitUI -framework MediaPlayer -framework MessageUI -framework QuartzCore -framework SystemConfiguration -framework FBSDKMessengerShareKit -framework UIKit -framework OpenGLES -framework OpenAL -framework GoogleMobileAds -lz -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.3/71c84df253d3ffb4f4d73375e8644512ff295e8f/gdx-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.3/71c84df253d3ffb4f4d73375e8644512ff295e8f/gdx-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d-platform/1.9.3/9f1d62485440239000f48f1d685246bef5272e21/gdx-box2d-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx-box2d.a -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks
[ERROR] Undefined symbols for architecture armv7:
[ERROR]   "_OBJC_CLASS_$_SFSafariViewController", referenced from:
[ERROR]       objc-class-ref in GoogleMobileAds(flat-armv7)
[ERROR]   "_OBJC_CLASS_$_CBUUID", referenced from:
[ERROR]       objc-class-ref in GoogleMobileAds(flat-armv7)
[ERROR]   "_OBJC_CLASS_$_CBCentralManager", referenced from:
[ERROR]       objc-class-ref in GoogleMobileAds(flat-armv7)
[ERROR]   "_CBCentralManagerOptionShowPowerAlertKey", referenced from:
[ERROR]       l892 in GoogleMobileAds(flat-armv7)
[ERROR] ld: symbol(s) not found for architecture armv7
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '"/Applications/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -o "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/IOSLauncher" -arch armv7 "-Wl,-filelist,/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/objects0" -L /Users/ibcmobile/.robovm-sdks/robovm-2.1.0/lib/vm/ios/thumbv7 -ObjC -Xlinker -alias_list -Xlinker "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/aliased_symbols" -exported_symbols_list "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/exported_symbols" -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-login/1.14.0/1a3cc419790b1abd94c4434cae633fd4e0082322/robopods-facebook-ios-login-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-share/1.14.0/3ebade83088ee749b6d74917b8b24a0b981b3cd4/robopods-facebook-ios-share-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-core/1.14.0/39470ef9e2ca5bc3c712c4d7818e56a6660cf01d/robopods-facebook-ios-core-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-messenger/1.14.0/7d9728a9f8fdf6f3a360aff264b6c6b1bcf7c05e/robopods-facebook-ios-messenger-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-bolts-ios/1.14.0/9af31651b319253310c5d34d265bb92de70ddfe7/robopods-bolts-ios-1.14.0.jar.extracted/META-INF/robovm/ios/libs "-F/Users/ibcmobile/Desktop/Platform Dash/ios/libs" -fPIC -miphoneos-version-min=7.0 -isysroot "/Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk" -lrobovm-bc -force_load /Users/ibcmobile/.robovm-sdks/robovm-2.1.0/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework FBSDKLoginKit -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreMotion -framework StoreKit -framework FBSDKShareKit -framework FBSDKCoreKit -framework Bolts -framework AdSupport -framework AudioToolbox -framework CoreTelephony -framework EventKit -framework EventKitUI -framework MediaPlayer -framework MessageUI -framework QuartzCore -framework SystemConfiguration -framework FBSDKMessengerShareKit -framework UIKit -framework OpenGLES -framework OpenAL -framework GoogleMobileAds -lz -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.3/71c84df253d3ffb4f4d73375e8644512ff295e8f/gdx-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.3/71c84df253d3ffb4f4d73375e8644512ff295e8f/gdx-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d-platform/1.9.3/9f1d62485440239000f48f1d685246bef5272e21/gdx-box2d-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx-box2d.a -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:344)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:268)
    at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:382)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:262)
    at org.robovm.compiler.Linker.link(Linker.java:421)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:465)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:768)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

**Comment by jkidi** [comment]
Make sure to include these frameworks in you robovm.xml:

```
    <framework>EventKit</framework>
    <framework>EventKitUI</framework>
    <framework>SafariServices</framework>
    <framework>CoreBluetooth</framework>
    <framework>MessageUI</framework>
    <framework>SystemConfiguration</framework>
    <framework>StoreKit</framework>
    <framework>AdSupport</framework>
    <framework>CoreTelephony</framework>
    <framework>CoreData</framework>
    <framework>CoreMedia</framework>
    <framework>MediaPlayer</framework>
```

Not exactly sure if all of these are necessary as I'm just copying this stuff from my own xml file.

**Comment by prakharprakhar89** [comment]
[ERROR] Undefined symbols for architecture armv7:
[ERROR]   "_OBJC_CLASS_$_SFSafariViewController", referenced from:
[ERROR]       objc-class-ref in GoogleMobileAds(flat-armv7)
[ERROR] ld: symbol(s) not found for architecture armv7
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '"/Applications/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -o "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/IOSLauncher" -arch armv7 "-Wl,-filelist,/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/objects0" -L /Users/ibcmobile/.robovm-sdks/robovm-2.1.0/lib/vm/ios/thumbv7 -ObjC -Xlinker -alias_list -Xlinker "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/aliased_symbols" -exported_symbols_list "/Users/ibcmobile/Desktop/Platform Dash/ios/robovm-build/tmp/Ios/ios/thumbv7/exported_symbols" -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-login/1.14.0/1a3cc419790b1abd94c4434cae633fd4e0082322/robopods-facebook-ios-login-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-share/1.14.0/3ebade83088ee749b6d74917b8b24a0b981b3cd4/robopods-facebook-ios-share-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-core/1.14.0/39470ef9e2ca5bc3c712c4d7818e56a6660cf01d/robopods-facebook-ios-core-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-facebook-ios-messenger/1.14.0/7d9728a9f8fdf6f3a360aff264b6c6b1bcf7c05e/robopods-facebook-ios-messenger-1.14.0.jar.extracted/META-INF/robovm/ios/libs -F/Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/org.robovm/robopods-bolts-ios/1.14.0/9af31651b319253310c5d34d265bb92de70ddfe7/robopods-bolts-ios-1.14.0.jar.extracted/META-INF/robovm/ios/libs "-F/Users/ibcmobile/Desktop/Platform Dash/ios/libs" -fPIC -miphoneos-version-min=7.0 -isysroot "/Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk" -lrobovm-bc -force_load /Users/ibcmobile/.robovm-sdks/robovm-2.1.0/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework FBSDKLoginKit -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreMotion -framework StoreKit -framework FBSDKShareKit -framework FBSDKCoreKit -framework Bolts -framework AdSupport -framework AudioToolbox -framework CoreTelephony -framework EventKit -framework EventKitUI -framework MediaPlayer -framework MessageUI -framework QuartzCore -framework SystemConfiguration -framework FBSDKMessengerShareKit -framework SafariServices -framework CoreBluetooth -framework CoreData -framework UIKit -framework OpenGLES -framework OpenAL -framework GoogleMobileAds -lz -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.3/71c84df253d3ffb4f4d73375e8644512ff295e8f/gdx-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.3/71c84df253d3ffb4f4d73375e8644512ff295e8f/gdx-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -force_load /Users/ibcmobile/.robovm/cache/ios/thumbv7/release/Users/ibcmobile/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d-platform/1.9.3/9f1d62485440239000f48f1d685246bef5272e21/gdx-box2d-platform-1.9.3-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx-box2d.a -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:344)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:268)
    at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:382)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:262)
    at org.robovm.compiler.Linker.link(Linker.java:421)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:465)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:768)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

PROJECT LEVEL GRADLE =======>

buildscript {
    project.ext.robopodsVersion = "1.14.0"
    project.ext.roboVMGradleVersion = "1.14.0"
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.mobidevelop.robovm:robovm-gradle-plugin:2.2.0-SNAPSHOT'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

```
version = '1.0'
ext {
    appName = "Platform Dash New"
    gdxVersion = '1.9.3'
    roboVMVersion = '2.2.0-SNAPSHOT'
    box2DLightsVersion = '1.4'
    ashleyVersion = '1.7.0'
    aiVersion = '1.8.0'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "https://oss.sonatype.org/content/repositories/releases/" }
}
```

}

project(":desktop") {
    apply plugin: "java"

```
dependencies {
    compile project(":core")
    compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
}
```

}

project(":android") {
    apply plugin: "android"

```
configurations { natives }

dependencies {
    compile project(":core")
    compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86_64"
    compile fileTree(dir: '../libs', include: '*.jar')
    compile 'com.google.android.gms:play-services-analytics:9.0.0'
    compile 'com.google.android.gms:play-services-ads:9.0.0'
    compile 'com.google.android.gms:play-services-plus:9.0.0'
    compile 'com.google.android.gms:play-services-games:9.0.0'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'

}


}
```

project(":ios") {
    apply plugin: "java"
    apply plugin: "robovm"

```
dependencies {
    compile project(":core")
    compile "com.mobidevelop.robovm:robovm-rt:$roboVMVersion"
    compile "com.mobidevelop.robovm:robovm-cocoatouch:$roboVMVersion"
    compile "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
    compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-ios"
    compile "org.robovm:robopods-google-mobile-ads-ios:$robopodsVersion"

    compile "org.robovm:robopods-facebook-ios:$robopodsVersion"

}
```

}

project(":core") {
    apply plugin: "java"

```
dependencies {
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    compile fileTree(dir: '../libs', include: '*.jar')
}
```

}

tasks.eclipse.doLast {
    delete ".project"
}

ROBOVM.XML================>

<config>
  <executableName>${app.executable}</executableName>
  <mainClass>${app.mainclass}</mainClass>
  <os>ios</os>
  <arch>thumbv7</arch>
  <target>ios</target>
  <iosInfoPList>Info.plist.xml</iosInfoPList>
  <resources>
    <resource>
      <directory>../android/assets</directory>
      <includes>
        <include>**</include>
      </includes>
      <skipPngCrush>true</skipPngCrush>
    </resource>
    <resource>
      <directory>data</directory>
    </resource>
    <resource>
      <directory>resource</directory>
    </resource>

  </resources>
  <forceLinkClasses>
    <pattern>com.badlogic.gdx.scenes.scene2d.ui._</pattern>
    <pattern>com.badlogic.gdx.graphics.g3d.particles.__</pattern>
    <pattern>com.android.okhttp.HttpHandler</pattern>
    <pattern>com.android.okhttp.HttpsHandler</pattern>
    <pattern>com.android.org.conscrypt._*</pattern>
    <pattern>com.android.org.bouncycastle.jce.provider.BouncyCastleProvider</pattern>
    <pattern>com.android.org.bouncycastle.jcajce.provider.keystore.BC$Mappings</pattern>
    <pattern>com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi</pattern>
    <pattern>com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$Std</pattern>
    <pattern>com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi</pattern>
    <pattern>com.android.org.bouncycastle.crypto.digests.AndroidDigestFactoryOpenSSL</pattern>
    <pattern>org.apache.harmony.security.provider.cert.DRLCertFactory</pattern>
    <pattern>org.apache.harmony.security.provider.crypto.CryptoProvider</pattern>
  </forceLinkClasses>
  <libs>
      <lib>z</lib>  
  </libs>
  <frameworkPaths>
    <path>libs</path>
  </frameworkPaths>

  <frameworks>
    <framework>EventKit</framework>
    <framework>EventKitUI</framework>
    <framework>SafariServices</framework>
    <framework>CoreBluetooth</framework>
    <framework>MessageUI</framework>
    <framework>SystemConfiguration</framework>
    <framework>StoreKit</framework>
    <framework>AdSupport</framework>
    <framework>CoreTelephony</framework>
    <framework>CoreData</framework>
    <framework>CoreMedia</framework>
    <framework>MediaPlayer</framework>

```
<framework>UIKit</framework>
<framework>OpenGLES</framework>
<framework>QuartzCore</framework>
<framework>CoreGraphics</framework>
<framework>OpenAL</framework>
<framework>AudioToolbox</framework>
<framework>AVFoundation</framework>
<framework>GoogleMobileAds</framework>
```

  </frameworks>

</config>

**Comment by Jjastiny** [comment]
Hey, this issue has to do with the new version of gpg.framework. I believe the bindings for robopods 1.14.0 is for version 2.0; however, the latest sdk you download from googles site is version 2.1 of gpg.framework. You'll need to fork the repository and change the bindings yourself since robopod will not be updated.

**Comment by Jjastiny** [comment]
Try this 

<unhideSymbols>
        <symbol>kGADErrorDomain</symbol>
        <symbol>kDFPSimulatorID</symbol>
        <symbol>kGADAdLoaderAdTypeNativeAppInstall</symbol>
        <symbol>kGADAdLoaderAdTypeNativeContent</symbol>
        <symbol>kGADAdLoaderAdTypeNativeCustomTemplate</symbol>
        <symbol>kGADAdSizeBanner</symbol>
        <symbol>kGADAdSizeLargeBanner</symbol>
        <symbol>kGADAdSizeMediumRectangle</symbol>
        <symbol>kGADAdSizeFullBanner</symbol>
        <symbol>kGADAdSizeLeaderboard</symbol>
        <symbol>kGADAdSizeSkyscraper</symbol>
        <symbol>kGADAdSizeSmartBannerPortrait</symbol>
        <symbol>kGADAdSizeSmartBannerLandscape</symbol>
        <symbol>kGADAdSizeInvalid</symbol>
        <symbol>GADAdSizeFromCGSize</symbol>
        <symbol>GADAdSizeFullWidthPortraitWithHeight</symbol>
        <symbol>GADAdSizeFullWidthLandscapeWithHeight</symbol>
        <symbol>GADAdSizeEqualToSize</symbol>
        <symbol>CGSizeFromGADAdSize</symbol>
        <symbol>IsGADAdSizeValid</symbol>
        <symbol>NSStringFromGADAdSize</symbol>
        <symbol>NSValueFromGADAdSize</symbol>
        <symbol>GADAdSizeFromNSValue</symbol>
        <symbol>kGADSimulatorID</symbol>
    </unhideSymbols>

<frameworks>
        <framework>AdSupport</framework>
        <framework>AudioToolbox</framework>
        <framework>AVFoundation</framework>
        <framework>CoreGraphics</framework>
        <framework>CoreMedia</framework>
        <framework>CoreTelephony</framework>
        <framework>EventKit</framework>
        <framework>EventKitUI</framework>
        <framework>MediaPlayer</framework>
        <framework>MessageUI</framework>
        <framework>QuartzCore</framework>
        <framework>StoreKit</framework>
        <framework>SystemConfiguration</framework>
    </frameworks>
